### ISSUE TITLE
Amazon Pay Button on Mobile Devices shows "InvalidButtonAccessRequest" Error

### ISSUE THREAD

**Issue by mrbeyondmedia** [amzn/amazon-payments-magento-2-plugin#1108]
When i try to us Amazon Pay Button on Mobile Devices i'll get an Error 
![IMG_0452](https://user-images.githubusercontent.com/37176962/152998638-712618a6-2844-4c64-85ce-271b1558fd91.jpg)

#### What I expected

Working Amazon Pay Button

#### What happened instead

Got an Error

#### Steps to reproduce the issue

Add Item to Cart and use den Amazon Pay Button in Minicart

#### Your setup

* Magento version: 2.3.6
* Amazon Pay Extension Version: 3.4.1-p3
* Magento Edition: Community

**Comment by sgabhart22** [comment]
Hello @mrbeyondmedia ,

I'd first suggest an upgrade to the Magento Marketplace version of our module, since it appears you are using the older version bundled with Magento. The newer release contains many bug fixes and security enhancements, and receives regular updates and maintenance. You can find detailed information on upgrading [here](https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html#composer-install-method).

You may also need to log into your Seller Central account and ensure the allowed javascript origins are set correctly in Integration Central > Manage Client/Store ID configurations.
