### ISSUE TITLE
Amazon Button not loading in minicart outside from checkout: Uncaught TypeError: Cannot read properties of undefined (reading 'quoteData')

### ISSUE THREAD

**Issue by rabillion** [amzn/amazon-payments-magento-2-plugin#1119]
#### What I expected

Amazon Pay Button is showing up in Minicart outside from checkout pages (e.g. Product page)

#### What happened instead

Amazon Button is not showing up outside from checkout and a console error appears (see screenshot). In Checkout/Cart it works fine.

#### Steps to reproduce the issue
Add product to cart from product page (or elsewhere). On every page except checkout and cart the error occurs and the amazon pay button does not showing up in minicart.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'quoteData')
    at quote.js:33:43
```
vendor/magento/module-checkout/view/frontend/web/js/model/quote.js Line 33:
quoteData = window.checkoutConfig.quoteData

When I block the amazon button's js scripts via the network tab (blocking network requests), the console error doesn't appear. 
![image](https://user-images.githubusercontent.com/16686371/159755696-10b68b2f-395c-43f3-99a0-c3b5ebea246e.png)

Is the error knowing issue and is there a solution?

#### Your setup

* Magento version: 2.3.5-p2
* Amazon Pay Extension Version: 5.9.1
* Magento Edition: Enterprise
* JavaScript Console: 
![image](https://user-images.githubusercontent.com/16686371/159752808-3cfd0e50-8a2c-45be-9711-a23fa84fb788.png)

Settings:
* Magento is in Developer Mode
* No merge or minify of js, no pagespeed module is enabled
* Amazon Sandbox mode is enabled
* Amazon Sign-in and show on Product page is disabled, Show in Minicart is enabled

**Comment by sgabhart22** [comment]
Hello @rabillion ,

No, this is not a known issue. Unfortunately I'm also unable to reproduce the problem on a clean 2.3.5-p2 installation with version 5.9.1 of the Amazon Pay module. The error is a little strange since it's happening in quote.js on the Product page, but I don't believe quote.js should be loaded by default outside of the checkout pages. Is it possible that a layout in a custom theme or component from a 3rd party plugin could be loading quote.js on pages where window.checkoutConfig is unavailable?

**Comment by christianzichichi** [comment]
Hi @rabillion ,
do you have any updates on this issue? Let us know if we can help in any way.

Thanks
Best

Christian
