### ISSUE TITLE
PWA Studio Integration

### ISSUE THREAD

**Issue by ptylek** [amzn/amazon-payments-magento-2-plugin#1133]
Hey,
Are there any plans to extend and prepare more details about [PWA Studio](https://developer.adobe.com/commerce/pwa-studio) integration of this Magento 2 plugin? I found [GraphQL API documentation](https://amzn.github.io/amazon-payments-magento-2-plugin/graphql-docs.html) but matching it together with [Amazon Pay developer docs](https://developer.amazon.com/docs/amazon-pay-checkout/overview.html) it's not as clear especially that the latter uses Amazon Pay SDK. Is the same functionality also prepared on the module so everything can be requested from Magento using GraphQL API?
I would be grateful for some more information in this matter.
Many thanks!

**Comment by sgabhart22** [comment]
Hello again @ptylek !

Yes, comparing the GraphQL docs with the AP dev docs could be a little difficult, since the Amazon Pay module deals with the SDK directly so the developer doesn't have to. Instead, I would recommend having a look at the Frontend Customisation section of the module documentation, specifically the [Notes on the Checkout Session API](https://amzn.github.io/amazon-payments-magento-2-plugin/customisation.html#notes) section and the example flow in [Configurable URLs](https://amzn.github.io/amazon-payments-magento-2-plugin/customisation.html#configurable-urls). You should be able to match most of the GraphQL queries/mutations pretty closely to the corresponding REST endpoints.

Also bear in mind that there are more details you'll have to handle yourself on the frontend side, such as placing and rendering the Amazon Pay button and handling the redirects. See [Add the Amazon Pay Button](https://developer.amazon.com/docs/amazon-pay-checkout/add-the-amazon-pay-button.html) for details on adding the Amazon Pay script, and do note that the module will generate the button payload and signature for you. You'll also need to make sure that your site can handle the various responses from Amazon throughout a checkout session by properly defining the Configurable URLs in your module configuration, and placing appropriate logic there to obtain the checkoutSessionId, redirect to your checkout URL, complete the checkout session, etc.

Please let us know if this helps,
Spencer

**Comment by ptylek** [comment]
Hey @sgabhart22, thanks for your reply, this is helpful and probably the only solution for now. 
Are there any plans to introduce extension that adds Amazon Pay payment option during checkout for PWA Studio in the future?

**Comment by sgabhart22** [comment]
@ptylek I don't believe there is anything concretely planned as far as developing an Amazon Pay extension specifically for the Venia theme/PWA studio right now. There are so many different frontend options that a development team can choose with a headless Magento implementation that we initially chose to keep the GraphQL implentation generic, and available to be used with whatever frontend framework a merchant might have.

If one of your goals is to display the AP button as a payment option, Lars Roettig has an excellent article on adding payment methods to the venia-ui checkoutPagePaymentTypes: https://larsroettig.dev/demystified-pwa-studio-checkout
