### ISSUE TITLE
No shipping methods found after returning from Amazon Pay login

### ISSUE THREAD

**Issue by liamfirth** [amzn/amazon-payments-magento-2-plugin#1145]
1. Add product to cart and proceed to checkout. 
2. Fill in customer details on shipping step and continue to payment step 
3. Select Amazon Pay as payment method and continue to Amazon Pay
4. Press "Continue as Customer Name" and return to checkout
5. Customer to be presented with a preselected address and a list of shipping options

<-- What actual results you or customer got -->

No shipping options are shown on return to checkout, instead "Sorry, no quotes are available for this order at this time" is shown and customer can't continue past shipping step.

#### Your setup

* Magento version: 2.4.5-p1
* Amazon Pay Extension Version:  5.14.1
* Magento Edition: Community
* Shop URL : https://hstv-dev.eddev.co[](url)
<img width="1552" alt="Screenshot 2022-11-14 at 3 08 19 pm" src="https://user-images.githubusercontent.com/6546226/201698664-412cfeff-2267-4e8f-b62f-edf79b635f96.png">
<img width="1552" alt="Screenshot 2022-11-14 at 3 23 55 pm" src="https://user-images.githubusercontent.com/6546226/201698682-6948b558-97b3-4dfa-94e0-686855a0a931.png">
<img width="1552" alt="Screenshot 2022-11-14 at 3 23 28 pm" src="https://user-images.githubusercontent.com/6546226/201698686-967f7112-228e-4df7-af71-33a282af3e00.png">
<img width="1552" alt="Screenshot 2022-11-14 at 3 23 04 pm" src="https://user-images.githubusercontent.com/6546226/201698696-f66bf3cc-4f8e-4ea1-a072-550effcfb204.png">

**Comment by sgabhart22** [comment]
Hello @liamfirth ,

There seems to be some issue with the template that's being used to render the Amazon Pay payment method; the AP button at the last step of checkout should be a Pay Now button, not an Express Checkout button. That is, once the user authenticates with Amazon, they should be presented with an Amazon-hosted payment screen where they can select the payment instrument to use and click a 'Pay Now' button to complete the transaction. Since the user already entered their address details in the shipping section of checkout, there's no need to redirect the user back there with Amazon address data. The address details that the user entered are supplied to Amazon in this flow.

The behavior of the button is determined by an attribute passed to the javascript component in the knockout template. If you look at the screenshot below:
![image](https://user-images.githubusercontent.com/13084014/201736396-d60511d8-c41c-48e7-bb90-b2e35db2ab85.png)

You can see that in the highlighted div (id 'PayWithAmazonButton'), the value for placement being passed to the amazon-button component is 'Checkout', when it should be 'PayNow' so that the button will use the correct payload to initiate a Pay Now checkout flow. Is it possible that any custom modules or theme code are overriding the default amazon-payment-method.html template? If not, then it may be possible that something odd happened with js bundling or minification that caused the confusion. If you don't believe any custom code could be responsible, it may be worthwhile to clear your static assets and redeploy your frontend code to see if this issue can resolve itself.

Let me know if this helps,
Spencer

**Comment by liamfirth** [comment]
Hi @sgabhart22 

That's right - I thought the custom templates had all been removed, but it looks like there was one with the Checkout and PayNow placements reversed. Thanks for your help!

Liam

**Comment by sgabhart22** [comment]
@liamfirth No problem at all! Glad it was a simple solution, and please don't hesitate to reach out with any future issues regarding the plugin.

Thanks,
Spencer
