### ISSUE TITLE
NOT show Amazon Pay button on Shipping Address portion of checkout

### ISSUE THREAD

**Issue by EmilyPepperman** [amzn/amazon-payments-magento-2-plugin#132]
Ability to disable and NOT to show Amazon Pay button on Shipping Address portion of checkout process. After upgrading to 1.1.4 now the Amazon Pay button shows on the Shipping Address area.

This confuses the customer... on the page beforehand the customer has the ability to choose what main payment method process they want to use. It is redundant to show it again here as well.

* Magento version: 2.1.8
* Magento Edition: Community
* Amazon Pay version: 1.1.4
* Shop URL : https://www.divegearexpress.com

![1 1 4amazon](https://user-images.githubusercontent.com/12411491/30440920-e7dcd8e0-9945-11e7-8581-e6ef75b195db.JPG)
![1 1 3amazon](https://user-images.githubusercontent.com/12411491/30440921-e7de3e9c-9945-11e7-832a-356253c32903.JPG)

**Comment by danielneu** [comment]
Hi @EmilyPepperman,

this is the intended behavior since the release of this extension.
If this wasn't showing for you before, then it was either removed manually or it did not show up as you are having overrides of the shipping.html in your theme.

We changed the way we are extending the shipping page in v1.1.4, to be more compatible with custom themes and 3rd party checkouts. I guess this is why it is now showing up for you.

This is the intended behavior, as Amazon Pay is only available in the cart for most merchants ( no mini-cart or product page entry point) and Magento 2 by default puts more emphasis on the checkout than the cart page.

![2017-09-15 09_47_58-home page](https://user-images.githubusercontent.com/10086275/30472005-20b9ddc4-99fb-11e7-8987-266dca490962.png)

If the mini cart Amazon Pay button was missing in the above screenshot, most customers would not see Amazon Pay, as it is more likely for them to click on the bulky checkout button than the small cart link.

Anyways, if you want to get rid of it, you will have to change this on your side.
It should be a simple change in this area: https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/src/Payment/view/frontend/layout/checkout_index_index.xml#L64
We are however happy to give better advise, if this is needed. Just get in touch with me or Matt.


Best wishes 
Daniel

**Comment by EmilyPepperman** [comment]
ok, one of our devs had hid it before... we have our main payment methods showing on our shopping cart page. We don't use the mini cart. I think I can hide it again. :-) We do have Amazon pay off right now... because of the login loop issue. I need to get it solved and turned back on. thanks for you help.
