### ISSUE TITLE
add order status for authorized transaction

### ISSUE THREAD

**Issue by ebaschiera** [amzn/amazon-payments-magento-2-plugin#187]
Hi,
when the module is configured to "Charge on shipment" (instead of "charge on order"), I would find very useful a different order status for when the payment is authorized and not yet captured.

By the way, why label that "Charge on shipment" when actually the capture takes place on invoice creation and not on shipment creation?

Thanks!
-Ermanno Baschiera

**Comment by RayAnaya** [comment]
I am going to go ahead and close this issue for now, as we have had a number of new releases and versions for both Magento 2 and the Amazon Pay plugin.

As far as the question being posed:  We call it "Charge on Shipment" because from what we have seen, most merchants choose to invoice and then immediately 'ship' a product once it's been paid.  While we could call it "Charge on invoice" we wanted to make sure it was clear that it should be charged *when* you are ready to ship,.
