### ISSUE TITLE
No ability to customise authorised (paid) order status?

### ISSUE THREAD

**Issue by craigcarnell** [amzn/amazon-payments-magento-2-plugin#224]
#### What I expected
Ability to specify new order status and authorised order status in the plugin admin.

In the Magento 1 version of the plugin it was possible to specify:
amazonpayments/general/new_order_status
amazonpayments/general/authorized_order_status

This allowed us to do something special when we have a customised authorized_order_status (in this case) - integrate to our warehouse.

#### What happened instead
No such setting

#### Your setup

* Magento version: 2.2.4
* Amazon Pay Extension Version: 
* Magento Edition: Enterprise

**Comment by craigcarnell** [comment]
Any updates on this issue? Amazon Pay cannot be used on our website until we can set the new order status after order placed.

**Comment by lemked** [comment]
Hi @craigcarnell ,

Sorry for the late reply. We will look into this and report back here.

**Comment by craigcarnell** [comment]
@lemked 

For your information, if you add order_status to adminhtml/system.xml, this will allow us to do this.

```
<field id="order_status" translate="label" type="select" sortOrder="4" showInDefault="1" showInWebsite="1" showInStore="0" canRestore="1">
                        <label>New Order Status</label>
<source_model>Magento\Sales\Model\Config\Source\Order\Status\Processing</source_model>
                    </field>
```

**Comment by lemked** [comment]
Hi @craigcarnell ,

After some investigation, it turned out that this was indeed a feature that was supported by our extension on versions below Magento 2.2.4. It was however removed in the meantime as there are future design changes in Magento 2, that discourage extensions (especially a bundled one such as ours) from changing the order status manually. Instead, the (payment) extension should change the payment status only and Magento 2 will react upon this.

The order status could still be changed with an override such as the one you have proposed. I'll close this issue as it is currently not planned to support such a feature in the future because of the reasons described above.

Kind regards,
Daniel
