### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by craigcarnell** [amzn/amazon-payments-magento-2-plugin#226]
I get this error on the home page of my test site:

Uncaught TypeError: Cannot read property 'match' of null
    at Object.t.K (eu.account.amazon.com/lwa/js/sdk/login1.js:45)
    at Object.window.amazon.Login.setClientId (eu.account.amazon.com/lwa/js/sdk/login1.js:59)
    at setClientId (/static/version1526484346/frontend/VaxLtd/uk/en_GB/Amazon_Payment/js/amazon-core.js:49)
    at window.onAmazonLoginReady (/static/version1526484346/frontend/VaxLtd/uk/en_GB/Amazon_Payment/js/amazon-core.js:36)
    at eu.account.amazon.com/lwa/js/sdk/login1.js:60
    at eu.account.amazon.com/lwa/js/sdk/login1.js:62

#### Your setup

* Magento version: 2.2.4

**Comment by lemked** [comment]
Hi @craigcarnell ,

Can you please provide the necessary steps to reproduce the problem?
If possible, please also attach a screenshot of the page where the error occurs.

Kind regards,
Daniel

**Comment by craigcarnell** [comment]
@lemked 

I haven't personally looked at this but one of my teams states:

It's caused by enabling 'Login with Amazon Pay'.

You have to setup "NO" in the config: Configuration >Sales > Payment Methods > Amazon pay > Advanced > Frontend > Login with Amazon available in authentication popup to disable this error.

**Comment by lemked** [comment]
Hi @craigcarnell ,

We can't reproduce this problem on a clean Magento 2.2.4 installation with the latest version of our extension installed.

Can you please provide additional information such as the version number of our extension, error logs, steps to reproduce the problem, screenshots, etc.? Otherwise it will be difficult to analyze the problem. If you have a test environment available where the problem can be reproduced, that would be great of course. In case that the test environment has an access restrictions, please drop us a note on payments-cp-devel@amazon.com and we can discuss on how to gain access.

Kind regards,
Daniel

**Comment by islandskater43** [comment]
M2.2.4 should be using v2.0.4 of our extension. @craigcarnell - can you confirm that is the right version? You can find the version by going to **Payment Methods > Amazon Pay > Developer Options**.

**Comment by craigcarnell** [comment]
@islandskater43 

```
Module version: 2.0.4
```

**Comment by craigcarnell** [comment]
@islandskater43 @lemked 

I believe this is caused by <referenceBlock name="authentication-popup" remove="true" /> in our custom theme.

We do not have customer logins on our site.

Perhaps your code should check, alternatively we can disable the option in your plugin and see if that resolves it.

**Comment by lemked** [comment]
Thanks @craigcarnell ,
We will investigate this issue and report back here.

**Comment by RayAnaya** [comment]
I am going to mark this issue as closed for now, as there have been numerous upgrades and new versions since it was initially reported.  Please feel free to re-open if you are still experiencing this issue!
