### ISSUE TITLE
javascript errors when deactivating the module in the backend - checkout blocker!

### ISSUE THREAD

**Issue by andidhouse** [amzn/amazon-payments-magento-2-plugin#241]
We deactivated the amazon pay module in the backend and expected - like any other payment extension before - the module and files are removed from the frontend.

in fact it broke our checkout completely with javascript errors so nobody can check out.
we deactivated the module in sandbox mode in the backend running the latest composer version and magento 2.2.2.

to bo honest - we will cancel amazon pay right now. there are just too many problems with this extension like orders which are payed but not in the magento2 backend, problems on checkout etc.

We really need a 100% reliable solution here - what at the moment amazon pay is not at all.

Thanks
![screen shot 2018-06-05 at 15 41 16](https://user-images.githubusercontent.com/16196483/40980818-a54c4812-68d9-11e8-9011-8c9778bdc1b4.png)

**Comment by andidhouse** [comment]
It also seems that amazon pay massively reduces site speed most on the cart page - it is a difference like day and night. With amazon pay installed the cart needs 2-3 seconds to load - without the extension is is way under one second.

It seems amazon pay is transferring the cart to the amazon server? Am i right? And if yes this would be a massive violation of the new European data policy law it think.

Anyway alone this makes the extension unusable for us.

**Comment by lemked** [comment]
Dear @andidhouse ,

I'm sorry that you are having issues with the Amazon Pay extension. 

The JavaScript error that you have encountered is a known issue that will be fixed with the next version of the extension. If you have a test environment available, we will gladly provide you instructions to install a beta release to verify whether it fixes the problem for you.

Regarding the performance issue: the extension should not slow down the cart page in this extend, so we would be interested to analyze this in detail. The JavaScript libraries for the Amazon Pay extension will usually load within a fraction of seconds and as they are loaded asynchronously, they shouldn't slow down the actual page rendering at all. As said, if you are encountering a different behavior, we would be interested in analyzing this. If you could provide an URL to verify this against, that would be great!

On your last point, regarding the cart contents: during checkout, Amazon Pay will receive the order total and the currency, which is required to complete the transaction of course. There is no detailed information about the cart contents transferred (item count, product names, individual prices, etc.).

I hope the provided information is helpful and sorry again for the problems that you've encountered while using the extension.

Kind regards,
Daniel

**Comment by andidhouse** [comment]
HI Daniel,

thanks for the info.
As i wrote we go now with another payment provider - simply too many bugs at the moment.

The javascript error - ok this is major. i am not shure if your testing here is enough? i mean if you do not test your extension to enable and disable in the backend what would you expect? This is one of the first things a extension developer should do to make shure if the extension is disabled in the backend no code etc. is any more put on the frontend.

Regarding the other issues i am afraid i can not give you any feedback here as we switch as mentioned to another payment provider.

Many thanks!

**Comment by lemked** [comment]
Hi @andidhouse ,

Thanks for your feedback.

We are constantly trying to improve the quality of the extension and of course you are right that there is still room for improvements. As said, the JS error when disabling the extension is something that we've already been looking into.

I'll leave this issue open until the fix is verified and available in a release branch.

Kind regards,
Daniel

**Comment by lemked** [comment]
Closing as this should not happen anymore with recent versions of our extensions that are bundled with Magento 2. Please re-open if problem persists.
