### ISSUE TITLE
[JP] Amazon Pay is stuck in sandbox environment

### ISSUE THREAD

**Issue by vincent-wantomo** [amzn/amazon-payments-magento-2-plugin#256]
What I expected
If Sandbox is disabled, I should be able to checkout with Live version.

What happened instead
Sandbox is always there even if disabled.

Steps to reproduce the issue
I identified the "issue" below, looks like a copy/paste issue.

The error occur from this file :

amzn/amazon-pay-and-login-magento-2-module/src/Core/Helper/Data.php

line 255 to 256

```
'jp' => 'https://origin-na.ssl-images-amazon.com/images/G/09/EP/offAmazonPayments/sandbox/prod' .
                '/lpa/js/Widgets.js?nomin',
```
WigetUrl for Sandbox and live is the SAME. Sandbox is always forced. I'm pretty sure this has never been tested for a japanese store because it's impossible to checkout. I tried to check other japanese EC websites and found the right widget URL below :

```
'jp' => 'https://origin-na.ssl-images-amazon.com/images/G/09/EP/offAmazonPayments/live/prod' .
                '/lpa/js/Widgets.js?nomin',
```
switch words : "sandbox" to "live"

Your setup
Magento version: 2.2.4
Magento Edition: Community
Country : JP
Thank you !

**Comment by lemked** [comment]
Dear @vincent-wantomo ,

Thanks for reporting this issue. A fix has been committed and will be available in the next version of our extension, that will be published along with Magento 2, version 2.2.5.

The issue has also been fixed in the non-bundled version of our extension, that will be published separately as version 1.0.7 for Magento 2 installations < v2.2.4.

Issue will remain open until both versions have been published.
