### ISSUE TITLE
Add configuration option for "Store Name"

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-2-plugin#34]
Amazon Payments sends emails to customers when an order is placed or funds are moved.
Those mails contain the name of the store, which is currently fixed as the name of the store (Magento 2 store name), see: 

https://github.com/amzn/amazon-payments-magento-2-plugin/blob/e703ca37fdb7b8ce84a8326e6ef6e5eaab9a838f/src/Payment/Model/OrderInformationManagement.php#L126

Please make this configurable, with the default being the store name of Magento, but add a text field from root to the store view level to override this.

Best wishes
Daniel

**Comment by danielneu** [comment]
The store name seems to be also used in emails, e.g. here: https://github.com/amzn/amazon-payments-magento-2-plugin/blob/e703ca37fdb7b8ce84a8326e6ef6e5eaab9a838f/src/Payment/view/frontend/email/hard-declined-auth.html

**Comment by lfritsche** [comment]
@danielneu hi there,

I'm facing the following behavior, which seems to be related to the store name configuration:

![image](https://user-images.githubusercontent.com/15127451/55875547-9a63d780-5b95-11e9-9eb3-171afa487f11.png)

Amazon Pay sends an Email after each order, with the order details and informations about the payment. The Store View name in this example was "Deutsch", while the name configured in the Amazon Pay Konfiguration at Magento was different. It seems like the extension still submits the Store View value instead of the configurable value for those Mails.

I'm using Magento 2.2.8
and the following Amazon Modules:

```
amzn/amazon-pay-and-login-with-amazon-core-module 2.1.3     Shared functionality for Amazon Pay and Login with Amazon modules
amzn/amazon-pay-module                            2.1.3     Amazon Pay module
amzn/amazon-pay-sdk-php                           3.4.1     Amazon Pay SDK (PHP)
amzn/login-with-amazon-module                     2.1.3     Login with Amazon module
```

composer update does not provide any updates for the amazon packages until I update to 2.3.

Any idea, whether this is still an old configuration not following the new option provided with the changes in the commit above?

Cheers - Leander

**Comment by lemked** [comment]
Hi @lfritsche ,

The configuration for the store name can be set individually for each store view. Can you please double check if the value "Deutsch" wasn't set for any of the views? Please also make sure that the relevant caches have been cleared.

Kind regards,
Daniel

**Comment by lfritsche** [comment]
Hi @lemked ,

thank's for the advice.
I've checked the settings and storeview settings are a good point, but the value was set to use the default value used at the general config level. Redeploys of the whole environment took place twice in the meantime and the wording remains the same (caching).

I have now set a value on the store view level and will test whether this would change the name in emails. 

Is there anything else I could check?

Regards,
Leander

**Comment by lemked** [comment]
Hi Leadner,

If it still doesn't work after this, my recommendation is to remove the store name from the configuration, clean the caches and check what will be sent now. If it's still the value "Deutsch", you should check if the "Display Name" in your Seller Central account doesn't actually has this set. This is the value that will be used as a default, if no store name is set at all. 

You can verify this by logging in to your Seller Central account > Settings > Account Info > Display Name:
![image](https://user-images.githubusercontent.com/4786477/56362165-851c2800-61e9-11e9-8d9a-e9a31960f778.png)

![image](https://user-images.githubusercontent.com/4786477/56362287-bdbc0180-61e9-11e9-80bd-c0198e0f4eb2.png)

**Comment by lfritsche** [comment]
Hi @lemked ,

I tried both options:
- adding the configuration on a store-view level (overwrite general configuration)
- removing all configurations, try using Amazon "Store details" default value

E-Mails still used the Store View Name:
![image](https://user-images.githubusercontent.com/15127451/56695005-5ff75000-66e8-11e9-872a-25c7a681bee2.png)

Any further idea?
Thanks!

**Comment by lemked** [comment]
Hi @lfritsche 

Can you grep for the value of the StoreView Name ("Deutsch") in your Magento 2 installation directory to check whether it shows up in any config file?

Kind regards,
Daniel

**Comment by lfritsche** [comment]
Hi @lemked 
unfortunately there's no such value within a file on the server/in Magento.
It is definitely using the store-view name.

Regards,
Leander

**Comment by lemked** [comment]
Hi @lfritsche ,

I've created a ticket with our support agency to investigate this issue. I'll get in touch by email for sharing access credentials etc.

Kind regards,
Daniel

**Comment by lemked** [comment]
Hi @lfritsche ,

Could you also double check if the store name is set correctly in Stores -> Configuration -> General -> Store Information for all store views?

![image](https://user-images.githubusercontent.com/4786477/58759219-cad94980-8526-11e9-82c0-08ddc78cdf7f.png)

If this is also not the solving the problem, please send us the credentials for the store backend of a staging instance where the problem can be reproduced to payments-cp-devel@amazon.com so that we can analyze the issue.

Kind regards,
Daniel

**Comment by lfritsche** [comment]
Hi @lemked 
The recent Update to Magento 2.2.9 solved this issue.
Thank's!

**Comment by lemked** [comment]
Thanks for the feedback @lfritsche , glad to hear the update could solve the issue for you!

Kind regards,
Daniel
