### ISSUE TITLE
Replace jquery/ui dependency for Magento 2.3.3 

### ISSUE THREAD

**Issue by fzemmel** [amzn/amazon-payments-magento-2-plugin#582]
The jQuery/ui library has been refactored into separate widgets so that core modules load only the widgets they need. This update improves the performance of core storefront tasks including the loading of category, configurable product, home, and checkout pages. 

Magento recommends that module developers update custom storefront code to remove the jquery/ui dependency. Otherwise, a performance degradation warning message might be displayed in the console.

https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-3-open-source.html#performance

![image](https://user-images.githubusercontent.com/11528935/68599461-e450cb00-04a0-11ea-921c-f985d23acc07.png)

#### Setup

* Magento version: 2.3.3
* Amazon Pay Extension Version: 
* Magento Edition: Enterprise

**Comment by tarishah** [comment]
Thank you @fzemmel, for getting this to our attention. 

We will try and get this fixed in the next Magento release.

**Comment by christianzichichi** [comment]
Hi @fzemmel ,

Thank you for your patience. The fix for this issue has been provided in this PR: https://github.com/amzn/amazon-payments-magento-2-plugin/pull/598/commits/1d65e2d0125848aaa57e3266bbbef3ecbfee98f7
it will be included in the next Magento release (2.3.5) and you can already find it in the latest release of our plugin (3.4.0) here: https://github.com/amzn/amazon-payments-magento-2-plugin

Thanks
Regards

Christian
