### ISSUE TITLE
Order total and the capture amount is different

### ISSUE THREAD

**Issue by rameshre-kensium** [amzn/amazon-payments-magento-2-plugin#589]
We expect the order total and the capture amount should be same.

But the capture amount is lesser than the order total.

This happens sometimes only.

* Magento version: 2.3.1
* Amazon Pay Extension Version:  3.1.4
* Magento Edition: Enterprise Cloud
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL :

**Comment by tarishah** [comment]
@rameshre-kensium can you please provide merchant details like merchant Id, orderIds and Amazon Pay logs at payments-cp-devel@amazon.com.

Thank you
Tarini

**Comment by rameshre-kensium** [comment]
Hi Tarishah ,

I have sent the details over the email(payments-cp-devel@amazon.com). Please check.

Thanks
Ramesh R

**Comment by rameshre-kensium** [comment]
Hi Tarishah

Any update on this?

Thanks

**Comment by amazon-pay** [comment]
Hi Ramesh,


Apologies!


I checked the order 000323978 in sellercentral - the order total and capture amount are the same, which is $257.67 (See attached)


Regards,?

Tarini

________________________________

**Comment by tarishah** [comment]
@rameshre-kensium I have provided a response via email.

**Comment by RayAnaya** [comment]
Marking this issue as resolved.

The root cause was that Magento Versions earlier than 2.3.2 did not properly handle carts with both bundled products and simple products, such that upon invoice generation - an invoice would only be generated for the bundled products and *1* of the simple products.

If anyone else has this issue, our recommendation is to move to Magento Version 2.3.2 or above!
