### ISSUE TITLE
Customers can't login after update

### ISSUE THREAD

**Issue by gewaechshaus** [amzn/amazon-payments-magento-2-plugin#69]
After updating to 1.1.1 customers can't login anymore.

#### What I expected
https://www.makerdise.com/customer/account/login/
Successfull login.

#### What happened instead
Failure message
     
    Fehler bei der Amazon-Anmeldung

#### Steps to reproduce the issue
Login via the URL provided above

#### Your setup
MCE 2.1.7
Haproxy -> Varnish -> Nginx -> php-fpm7.0

**Comment by danielneu** [comment]
Hi Jan,

we have not seen this before and do not see it on a vanilla Magento 2.1.7 CE installation, either.
I just double checked this.

I can see some parts of the language we are using has not been updated in your shop, it e.g. still says "Mit Amazon Payments ..." while the new version, since 1.1.0 should say "Mit Amazon Pay und Login mit Amazon ...".

Are you sure the installation was completed successfully and all caches are fresh? No better idea at this time.

Best wishes 
Daniel

**Comment by gewaechshaus** [comment]
Hi Daniel,

I'm going to check it now... Till later

**Comment by gewaechshaus** [comment]
It looks like I got old ressources in my composer.json, I am actualy updating.

**Comment by gewaechshaus** [comment]
Hi @danielneu,

this can be closed as I got the new and the old Version(before renaming) running in parallel as I did forget to remove the related line in composer.json. This was causing those issues...
Damn stupid, sorry!

**Comment by danielneu** [comment]
Thanks for reporting back, glad this is solved.

Best wishes 
Daniel
