### ISSUE TITLE
Payment not visible for virtual product (gift card)

### ISSUE THREAD

**Issue by tomaszbec** [amzn/amazon-payments-magento-2-plugin#719]
**What I expected**
Amazon Pay method should be visible for virtual products (gift cards). 

**What happened instead**
Payment not visible for virtual product (gift cards).

**Steps to reproduce the issue**
After installing plugin on Magento 2.3.3 and adding virtual product to the cart, Amazon Pay button is not visible.

I see that it's blocked in the plugin, but why ? 
If I add other (not virtual product) It works fine.

**Magento setup:**
Magento version: 2.3.3
Amazon Pay Extension Version: 3.3.1
Magento Edition: Community

**Comment by christianzichichi** [comment]
Hi @tomaszbec ,
thanks for contacting us. Unfortunately our in-core plugin does not support virtual products.
We recommend installing the new version of our plugin, which supports both physical and virtual products, following the instructions in the README here:

https://github.com/amzn/amazon-payments-magento-2-plugin/tree/V2checkout-1.2.x

Thanks
Regards

Christian

**Comment by moElwan** [comment]
Hello @christianzichichi, Thanks for the clarification.
Is there any way to support virtual products on M2.4 please?
I see the [V2checkout-1.2.x](https://github.com/amzn/amazon-payments-magento-2-plugin/tree/V2checkout-1.2.x) is only for `from 2.2.6 up to 2.2.11` 
Thank you

**Comment by salesigniter** [comment]
Your v2 module supports virtual products according to this thread. I have installed the latest version 5.14.1

With a regular product the amazon pay button shows: https://www.screencast.com/t/HIzWNLLEe

With virtual it does not: https://www.screencast.com/t/9VSni91JiUh

We use the latest version of Amasty One Step Checkout, but it seems it uses regular XML of checkout_index_index.xml so I don't think that's the problem. 

Can you help so that the button shows up? 

I have also emailed payments-cp-devel@amazon.com but have not heard back.
