### ISSUE TITLE
Uncaught TypeError: Cannot read property 'duration' of undefined

### ISSUE THREAD

**Issue by haneef-faisal** [amzn/amazon-payments-magento-2-plugin#864]
Magento v2.3.5-p1
PHP Version: 7.2.33
PHP Memory Limit: 2048M

Modules Enabled
Amazon_Core
Amazon_Login
Amazon_Payment
Amazon_PayV2

Module Configuration
Payment Action: Charge on Order
Authorization Mode: Automatic
Enable Alexa Notifications: Yes

Advanced

Front-End
Module version: 1.5.0
Button Color: Gold
Show Amazon Pay button on product page: Yes
Show Amazon Pay button in minicart: Yes
Show Amazon Pay in payment methods: Yes

Sales Options
Store Name: Company Name
Restrict Product Categories: None

Shipping Restrictions
Restrict PO Boxes: No
Restrict Packstations: No

Developer Options
Logging: Yes
Checkout review URL: {empty}
Checkout result URL: {empty}
Allowed IPs: {empty}
Developer Logs: Client V2 Log

Buttons don't load on any page. Seeing this error:

checkout.js:1 Uncaught TypeError: Cannot read property 'duration' of undefined
    at _t (checkout.js:1)
    at Object.Ae [as renderButton] (checkout.js:1)
    at amazon-button.js:91
    at $.<computed>.<computed>.<anonymous> (amazon-button.js:36)
    at checkout-session-config-load.js:47
    at $.<computed>.<computed>._loadButtonConfig (amazon-button.js:34)
    at $.<computed>.<computed>._loadButtonConfig (widget.js:100)
    at $.<computed>.<computed>.<anonymous> (amazon-button.js:90)
    at amazon-checkout.js:49
    at Object.execCb (de64f5b95f673743303b0a511196b583.js:1650)

**Comment by christianzichichi** [comment]
Hi @haneef-faisal ,
thanks for contacting us. The reported JS console error is a known issue on product level and is not caused by the plugin itself. Nevertheless, the error does not prevent buttons to load and does not affect the plugin functionalities. The plugin has been developed and tested on Luma standard template and this issue seems template-specific. I'd ask you to provide details regarding the staging environment at payments-cp-devel@amazon.com. We'll be able to provide further support from there.

Thanks a lot
Best
Christian
