### ISSUE TITLE
Version update and Uninstall infos

### ISSUE THREAD

**Issue by andidhouse** [amzn/amazon-payments-magento-2-plugin#87]
Hi there,

i think the new version should always also be promoted here right:

https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html
Today it says:
Install the extension via composer: composer require amzn/amazon-payments-magento-2-plugin:^1.1.1

But it should be Install the extension via composer: composer require amzn/amazon-payments-magento-2-plugin:^1.1.2 

Or am i wrong?

I also would like to suggest to ad a section for uninstallation - this is important if any conflicts are present.

composer remove...

Is the new version 1.1.2 available via composer today? So nothing needs to be loaded on the server right? Just run the command 

composer require amzn/amazon-payments-magento-2-plugin:^1.1.2 

from the command line and then activate the module etc.?

Thanks!

**Comment by danielneu** [comment]
Hi @andidhouse 

composer require amzn/amazon-payments-magento-2-plugin:^1.1.1

Means: Install the Amazon Pay module in version 1.1.1 or above, with above being non-breaking changes according to the semantic versioning convention.

This way you just run a composer update and always get the newest version without looking out for it and updating your composer manually.

I am marking this ticket as a request for documentation improvement, I will call this out in the docs and also add information for uninstalling.

The module in version 1.1.2 can be installed via composer since yesterday and will soon also be on the marketplace.

Best wishes 
Daniel

**Comment by danielneu** [comment]
To Do:

* Add uninstall section
* Improve installation via composer explanation to call out the automatic version update and explain how to fix the version.

BTW: A PR is always welcome as well.

Best wishes 
Daniel

**Comment by andidhouse** [comment]
HI Daniel,

thanks for the great and fast reaction. Shure next time to create a PR - your right.

So now i get it!
composer update updates all modules i think (which may be not welcome at a time). To just update the amazon module it is then 

composer update amzn/amazon-payments-magento-2-plugin ?

**Comment by danielneu** [comment]
I'm not a composer expert and did not try this myself, but that's hat others suggest as well, e.g. on SO:
https://stackoverflow.com/questions/19148727/how-would-i-only-update-one-composer-dependency

Best wishes 
Daniel
