### ISSUE TITLE
Redirected to empty cart page after payment

### ISSUE THREAD

**Issue by benjamin-volle** [amzn/amazon-payments-magento-2-plugin#900]
#### What I expected

Redirect to order confirmation page after paying with Amazon Pay V2

#### What happened instead

Redirected to empty cart page

#### Steps to reproduce the issue

Just make an order on frontend

#### Your setup

* Magento version: 2.3.5-p2
* Amazon Pay Extension Version: branch dev-V2checkout-1.2.x
* Magento Edition: Enterprise

In fact, the module has a problem when an instruction like 
`{{block class="Magento\\Cms\\Block\\Block" area="frontend" block_id="email-footer"}}` is included in header or footer of emails.

I cannot exaplain it, but we could reproduce it on 2 different sites and on a standard version of Magento.

Does someone have already experienced such issue ? If so, how to solve it ?

Benjamin

**Comment by jaybeckr** [comment]
Hi @benjamin-volle - please let me know:

- which commit of the `V2checkout-1.2.x` branch you are using
- is there anything "interesting" in `var/log/paywithamazon_v2.log` when you see this behavior?
- I don't quite follow the email issue, the module should not do anything to impact email

**Comment by benjamin-volle** [comment]
Hey,

- We are on 15d3e664cd7d0c7e8117a750e46edfc4e89a94f2
- Nothing relative to error or something like that
- In fact I guess this is more a Magento issue than in your module. There is something with sessions that prevent magento to validate the cart here : `\Magento\Checkout\Controller\Onepage\Success::execute`  if there is a "{{block}}" instruction in header or footer of emails when choosing Amazon Pay payment.

I know that it looks crazy but this is the case :/

**Comment by jaybeckr** [comment]
Thanks for the update. I have tested with a clean Magento 2.3.5-p2 site (created using `composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition www`) with the same CV2 version and got to the checkout success page after placing an order. You mentioned you reproduced it on "a standard version of Magento", is that environment without any extra modules installed?

Does this only happen when you have the email footer block inserted to emails? When the order is placed it sends an email, if that process is throwing an error for some reason (even unrelated to the Amazon Pay module itself) it could cause the flow to error, and would likely result in not reaching the order success page. Are there any errors in var/log/exception.log when you try to place an order? Also curious, assuming this is a development site - if you enable a payment method like Check/Money Order, does it get to the success page?

**Comment by jaybeckr** [comment]
@benjamin-volle - quick update, I _have_ in fact been able to repro this. As you said, only when you have an email including a block. Everything appears to work correctly, the order is placed, the order email goes out (with the included block contents), and you are sent to `/checkout/onepage/success`... but then immediately redirected to the cart.

I've traced the cart redirection to `magento/module-checkout/Model/Session/SuccessValidator.php`, it's checking `$this->checkoutSession->getLastSuccessQuoteId()` and it is getting null, so then the checkout Onepage/Success controller redirects to the cart.

Super odd that it only happens if that block is included, I traced through where the last success quote ID is set in `magento/module-quote/Model/QuoteManagement.php::placeOrder()` and it sets a value there. Somehow between there and the success controller the value is lost however. But only when the email includes the cms block?!?!?!?

I will continue to investigate a bit, on the one hand I don't see how this could be an Amazon Pay issue, but on the other hand it doesn't affect check / money order payments.

**Comment by jaybeckr** [comment]
I'm at a bit of a loss here, will need to think on this some more:
![image](https://user-images.githubusercontent.com/20869477/94630682-1a02cc00-028c-11eb-94e6-761126a92208.png)

**Comment by benjamin-volle** [comment]
Ho @jaybeckr , yeah it also drove me crazy seeing this issue ! I will also try to investigate on my side but at this moment iI don't really have any lead for it.
If you need anything from me just let me know !

**Comment by jaybeckr** [comment]
@benjamin-volle - we have a fix for this, will get an update available for you. If you're comfortable trying out the change manually to see if it fixes it for you, check out https://github.com/amzn/amazon-payments-magento-2-plugin/pull/905.

**Comment by christianzichichi** [comment]
@benjamin-volle  the bugfix has been merged. You may reinstall the plugin to have it included. Please confirm if the issue is solved

Thanks
Best
Christian

**Comment by benjamin-volle** [comment]
Heu guys, I can confirm it solved the issue, thank you very much !
