### ISSUE TITLE
[Bug] base_original_price and original_price empty in sales_order_item

### ISSUE THREAD

**Issue by michaelscheel** [amzn/amazon-payments-magento-2-plugin#992]
#### What I expected

base_original_price and original_price have to be filled after completing an order

#### What happened instead

fields are empty or zero (same bug as fixed here: https://pluginarchive.com/magento/creativestyle_amazonpayments/v/1-8-4)

#### Steps to reproduce the issue

1. Checkout any items with Amazon Pay

#### Your setup

* Magento version: 2.2.11
* Amazon Pay Extension Version: V2checkout-1.2.x / 1.1.10
* Magento Edition: Community

**Comment by jaybeckr** [comment]
Hi @michaelscheel , thanks for your report. Just to be sure we're looking at the same thing, you are referring to the `sales_order_item` table and looking for the `base_original_price` / `original_price` columns to not be empty or zero?

Are these items simple products, and what is your currency configuration like? In my test environment with V2checkout-1.2.x both of those columns have data for all test orders, but I can try to replicate more closely what your config is.

Finally, it looks like your module version is quite out of date, there have been many fixes and improvements since 1.1.0 and I highly recommend updating to the current V2checkout-1.2.x branch.

**Comment by michaelscheel** [comment]
Hi @christianzichichi, we're using the most up-to-date version, but we're constrained to keep Magento 2.2 branch. Yes, I'm referring to sales_order_item. Product type doesn't matter, currency is EUR.

**Comment by christianzichichi** [comment]
Hi @michaelscheel ,
can you please reach out to payments-cp-devel@amazon.com? We would need more details about your installation.

Thanks
Best
Christian

**Comment by jajajaime** [comment]
Hi @michaelscheel,

I was able to replicate your issue on 2.2.6 and 2.2.11, but not on 2.3.x or 2.4.x.
After some investigation I noticed that Magento does not persist the original prices on quote items, and calculates them every time the app loads within its quote collectTotals which subsequently calls _calculateRowTotal for each item.
Magento "fixed" this issue by adding this collectTotals close to the top of the placeOrder method
https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Quote/Model/QuoteManagement.php#L353

We will be dropping support for 2.2.x Magento versions at the end of the year, so we won't be fixing this.

One easy way that you can solve this is by creating a before plugin to the placeOrder method that just collects quote totals.

Regards,

Jaime Lopez

**Comment by jajajaime** [comment]
Hi @michaelscheel,

Scratch the above. We will be fixing this as it actually does affect 2.3.0. We will be creating a PR soon for the fix.

If really needed in the meantime, please implement the solution described in my previous comment.

**Comment by christianzichichi** [comment]
hi @michaelscheel ,
the issue has been solved here: https://github.com/amzn/amazon-payments-magento-2-plugin/pull/1007
please reinstall v2checkout-1.2.x branch

Thanks
Best
Christian
